### PR TITLE
Update to 2.5.0

### PR DESCRIPTION
**Pull request by jsnedeco**
I think this loses some of the efficiency vs. the old one because of the way the thermodynamic parameters are loaded, but it works, passes all tests and seems to behave more or less. I mostly wanted to be able to use the masking capabilities.

### CODE REVIEW

**Comment by grinner** [comment]
Hi @jsnedeco.  Great PR
Thanks for the kick in the pants to get @benpruitt and I back on this.

We think this PR is a great start to push us to a 1.0.0 release.

We've gone ahead and created `1.0.0-staging` branch which we would like you to re-point your PR to.

Things we plan on adding:

- `README` and `CONTRUBUTIONS` updates
- Github Action CI / CD
- [pre-commit](https://pre-commit.com) hooks
- Test updates


Prior to a full review of this PR we have a few notes / comments:

1.  `git rm src/thermoanalysis.c` Since it is our pattern to no commit cython compilation assets to the repo

2.  We'll squash your 16 commits down to 1 for the merge.  Feel free to interactive rebase down to one commit i.e. `git rebase -i HEAD~16`.  If you aren't comfortable doing this, either @benpruitt or I can advise on this process.

3. Remove trailing white space.  This is a tricky one that your IDE/text editor can support.  (note: We are going to add support to manage this automatically downstream).  Looks like `primer3` source code does this but it causes a big diff. It's debatable if we should leave it as is and just import `primer3` as is.

4. Add an exception type to this block in `thermoanalysis.pyx`
    
```python
try:
    tr_obj.ascii_structure = tr_obj.thalres.sec_struct.decode('UTF-8')
except:
    return tr_obj
```

to 
```python
try:
    tr_obj.ascii_structure = tr_obj.thalres.sec_struct.decode('UTF-8')
except <Whatever exception you expect here>:
    return tr_obj
```

5. In `primerdesign_py.c`, `destroy_secundary_structures(pa, retval);` where does this function live? ?

6. Looks like `primer3` changed indents from tab/space hybrid to spaces


Thanks again for getting this started!

**Comment by grinner** [comment]
Hi @jsnedeco.  Great PR
Thanks for the kick in the pants to get @benpruitt and I back on this.

We think this PR is a great start to push us to a 1.0.0 release.

We've gone ahead and created `1.0.0-staging` branch which we would like you to re-point your PR to.

Things we plan on adding:

- `README` and `CONTRUBUTIONS` updates
- Github Action CI / CD
- [pre-commit](https://pre-commit.com) hooks
- Test updates


Prior to a full review of this PR we have a few notes / comments:

1.  `git rm src/thermoanalysis.c` Since it is our pattern to no commit cython compilation assets to the repo

2.  We'll squash your 16 commits down to 1 for the merge.  Feel free to interactive rebase down to one commit i.e. `git rebase -i HEAD~16`.  If you aren't comfortable doing this, either @benpruitt or I can advise on this process.

3. Remove trailing white space.  This is a tricky one that your IDE/text editor can support.  (note: We are going to add support to manage this automatically downstream).  Looks like `primer3` source code does this but it causes a big diff. It's debatable if we should leave it as is and just import `primer3` as is.

4. Add an exception type to this block in `thermoanalysis.pyx`
    
```python
try:
    tr_obj.ascii_structure = tr_obj.thalres.sec_struct.decode('UTF-8')
except:
    return tr_obj
```

to 
```python
try:
    tr_obj.ascii_structure = tr_obj.thalres.sec_struct.decode('UTF-8')
except <Whatever exception you expect here>:
    return tr_obj
```

5. In `primerdesign_py.c`, `destroy_secundary_structures(pa, retval);` where does this function live? ?

6. Looks like `primer3` changed indents from tab/space hybrid to spaces


Thanks again for getting this started!

**Comment by benpruitt** [comment]
`primer3-py` now includes `primer3` `v2.6.1` as of the [v1.0.0 release](https://github.com/libnano/primer3-py/releases/tag/v1.0.0)

**Comment by jsnedeco** [comment]
Only took two years to find out about this, but GitHub never sent me any notifications about this! Thank you so much for running with my change and doing the actual work to get it done the right way!

**Pull request closed without merging**
